name: CI for Main

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Exécute en premier
  job1:
    if: |
      contains(github.event.head_commit.message, 'Merge pull request') ||
      contains(github.event.head_commit.message, 'Merge branch')
    runs-on: ubuntu-latest
    steps:
      - name: Step in Job 1
        run: echo "This is Job 1"

  # Job 2: Exécute en parallèle avec Job 1
  job2:
    if: |
      contains(github.event.head_commit.message, 'Merge pull request') ||
      contains(github.event.head_commit.message, 'Merge branch')
    runs-on: ubuntu-latest
    steps:
      - name: Step in Job 2
        run: echo "This is Job 2"

  # Job 3: Dépend de Job 1 et Job 2
  job3:
    needs:
      - job1
      - job2
    if: |
      contains(github.event.head_commit.message, 'Merge pull request') ||
      contains(github.event.head_commit.message, 'Merge branch')
    runs-on: ubuntu-latest
    steps:
      - name: Step in Job 3
        run: echo "This is Job 3, after Job 1 and Job 2"

  # Job 4: Dépend de Job 3
  job4:
    needs: job3
    if: |
      contains(github.event.head_commit.message, 'Merge pull request') ||
      contains(github.event.head_commit.message, 'Merge branch')
    runs-on: ubuntu-latest
    steps:
      - name: Step in Job 4
        run: echo "This is Job 4, after Job 3"

  # Job 5: Dépend de Job 4
  job5:
    needs: job4
    if: |
      contains(github.event.head_commit.message, 'Merge pull request') ||
      contains(github.event.head_commit.message, 'Merge branch')
    runs-on: ubuntu-latest
    steps:
      - name: Step in Job 5
        run: echo "This is Job 5, after Job 4"